repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-corgisnps_logo_light.png
    - docs/images/nf-core-corgisnps_logo_light.png
    - docs/images/nf-core-corgisnps_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - CITATIONS.md
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-corgisnps_logo_light.png
    - docs/images/nf-core-corgisnps_logo_light.png
    - docs/images/nf-core-corgisnps_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: DOH-JDJ0303
  name: CorgiSNPs
  description: Core genome analysis workflow for fungal pathogens
  author: Jared Johnson
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - gpu
    - citations
    - documentation
    - rocrate
  is_nfcore: false
